// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc/gpt.proto

package GPT

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MaxUnit    uint64 `protobuf:"varint,2,opt,name=maxUnit,proto3" json:"maxUnit,omitempty"`
	UnitUser   uint64 `protobuf:"varint,3,opt,name=unitUser,proto3" json:"unitUser,omitempty"`
	ExpiryTime uint64 `protobuf:"varint,4,opt,name=ExpiryTime,proto3" json:"ExpiryTime,omitempty"`
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_grpc_gpt_proto_rawDescGZIP(), []int{0}
}

func (x *AskResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AskResponse) GetMaxUnit() uint64 {
	if x != nil {
		return x.MaxUnit
	}
	return 0
}

func (x *AskResponse) GetUnitUser() uint64 {
	if x != nil {
		return x.UnitUser
	}
	return 0
}

func (x *AskResponse) GetExpiryTime() uint64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

type AskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_grpc_gpt_proto_rawDescGZIP(), []int{1}
}

func (x *AskRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_grpc_gpt_proto protoreflect.FileDescriptor

var file_grpc_gpt_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x67, 0x70, 0x74, 0x22, 0x77, 0x0a, 0x0b, 0x41, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x55,
	0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x55, 0x6e,
	0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x20,
	0x0a, 0x0a, 0x41, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x32, 0x38, 0x0a, 0x0a, 0x47, 0x70, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a,
	0x0a, 0x03, 0x41, 0x73, 0x6b, 0x12, 0x0f, 0x2e, 0x67, 0x70, 0x74, 0x2e, 0x41, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x70, 0x74, 0x2e, 0x41, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x47, 0x52, 0x50, 0x43, 0x2f, 0x47, 0x50, 0x54, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grpc_gpt_proto_rawDescOnce sync.Once
	file_grpc_gpt_proto_rawDescData = file_grpc_gpt_proto_rawDesc
)

func file_grpc_gpt_proto_rawDescGZIP() []byte {
	file_grpc_gpt_proto_rawDescOnce.Do(func() {
		file_grpc_gpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_gpt_proto_rawDescData)
	})
	return file_grpc_gpt_proto_rawDescData
}

var file_grpc_gpt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_gpt_proto_goTypes = []interface{}{
	(*AskResponse)(nil), // 0: gpt.AskResponse
	(*AskRequest)(nil),  // 1: gpt.AskRequest
}
var file_grpc_gpt_proto_depIdxs = []int32{
	1, // 0: gpt.GptService.Ask:input_type -> gpt.AskRequest
	0, // 1: gpt.GptService.Ask:output_type -> gpt.AskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_gpt_proto_init() }
func file_grpc_gpt_proto_init() {
	if File_grpc_gpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_gpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_gpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_gpt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_gpt_proto_goTypes,
		DependencyIndexes: file_grpc_gpt_proto_depIdxs,
		MessageInfos:      file_grpc_gpt_proto_msgTypes,
	}.Build()
	File_grpc_gpt_proto = out.File
	file_grpc_gpt_proto_rawDesc = nil
	file_grpc_gpt_proto_goTypes = nil
	file_grpc_gpt_proto_depIdxs = nil
}
